import { React, useEffect, useState } from "react";
import { Button } from "components/ui/Button";
import "styles/views/Game.scss";
import "styles/views/GameRoom.scss";
import PresentationContainer from "components/ui/PresentationContainer";
import TextPrompt from "models/TextPrompt"
import DrawingPrompt from "models/DrawingPrompt"
import { CountdownCircleTimer } from "react-countdown-circle-timer";
import AudioContextEnum from "../../helpers/audioContextEnum";
import AudioPlayer from "../../helpers/AudioPlayer";
import DrawContainer from "components/ui/DrawContainer";
import Leaderboard from "components/ui/Leaderboard";
import User from "../../models/User";
import { unescapeLeadingUnderscores } from "typescript";
import { BurgerMenu } from "components/ui/BurgerMenu";
import Menu from "components/ui/Menu";
import BaseContainer from "components/ui/BaseContainer";


const minuteSeconds = 60;
const startTime = Date.now() / 1000; // use UNIX timestamp in seconds
const endTime = startTime + 10; // use UNIX timestamp in seconds

const remainingTime = endTime - startTime;

const timerSound = new AudioPlayer(AudioContextEnum.TIMER);

const SandboxView = () => {

    const [openMenu, setOpenMenu] = useState<boolean>(false);

    const toggleMenu = () => {
        setOpenMenu(!openMenu);
    }

    const response = [
        {
            "textPromptId": 1,
            "content": "A funny looking dog with a round hat on a tree. With curious looking eyes in a house of seven people",
            "creator": {
                "userId": 3,
                "nickname": "Greta",
                "creationDate": "2024-04-25",
                "status": "OFFLINE",
                "persistent": null,
                "email": null,
                "password": null,
                "avatarId": 1,
                "role": "admin",
                "token": "79e902ba-5a46-4329-b2b0-1549eb46766d",
                "gameRoom": null
            },
            "gameSession": {
                "gameSessionId": 1,
                "creationDate": "2024-04-25",
                "token": "0d529e1d-2d4c-4d41-b43e-f57b53c307a9",
                "status": "IN_PLAY",
                "usersInSession": [
                    3,
                    6
                ],
                "roundCounter": 8,
                "currentIndex": 0,
                "gameLoopStatus": "PRESENTATION"
            },
            "assignedTo": 6,
            "previousDrawingId": 776,
            "nextDrawingId": 2,
            "round": 1
        },
        {
            "drawingId": 2,
            "encodedImage": "\"iVBORw0KGgoAAAANSUhEUgAAAlgAAAGQCAYAAAByNR6YAAAAAXNSR0IArs4c6QAAH9lJREFUeF7t3T+sJtdZB+A3DshmbTm2hGShdWE6Ghy5p1hALhBOQU0ChMUkkEQUaSgsCuSCJgVKSOx4DUS4oE8QhQVxQW9hKkRBiiCBhBQnsk2smJg95l775vr+mW/mN/OdmXlWihStZ9455znv3vvTzHzn+0j5Q4AAAQIECBAgEBX4SLSaYgQIECBAgAABAiVgaQICBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOAAECBAgQICBg6QECBAgQIECAQFhAwAqDKkeAAAECBAgQELD0AAECBAgQIEAgLCBghUGVI0CAAAECBAgIWHqAAAECBAgQIBAWELDCoMoRIECAAAECBAQsPUCAAAECBAgQCAsIWGFQ5QgQIECAAAECApYeIECAAAECBAiEBQSsMKhyBAgQIECAAAEBSw8QIECAAAECBMICAlYYVDkCBAgQIECAgIClBwgQIECAAAECYQEBKwyqHAECBAgQIEBAwNIDBAgQIECAAIGwgIAVBlWOwAICP1VVt6vqqap6oqpunlzzP6rq1ar6VlW9ePJ3yePeWWBuLkGAAIFNCAhYm1hGk9iQwHXh6fWqerKqHrlmzj84+e8Pho77r6r6k6pqPzOuC3aC2IYa0lQIEBgnIGCNc3MWgTkEfq+qnh0Qnua4dqpmC2LPVNWdVEF1CBAgsEYBAWuNq2bMWxT4clV9fkMTe6Wq3rjmEaY7XRtacFMhQOAnBQQsHUHg+AJbC1dDRN3pGqLkGAIEVisgYK126Qx8IwLtseALG5nLmGm40zVGzTkECHQvIGB1v0QGuFKB615Wb5/0+0ZVfWfl71zNvTzudM0trD4BArMICFizsCq6c4GhL6u3T/pd9ym/nVO+P/2vVNUXYBAgQGAtAgLWWlbKONcisMf3qZZamzer6v6Ti53f88sL80utgusQIDBIQMAaxOQgAoMEhKtBTPGDPEaMkypIgMBUAQFrqqDzCfy/wN5fVu+hDzxG7GEVjIEAgfcEBCyNQGC4wFUvrv9sVd07vJQjZxTw+HBGXKUJEBgmIGANc3IUgaEvrpPqS8Djw77Ww2gI7EZAwNrNUpvoBAHvVk3A6+RUjw87WQjDILAXAQFrLyttnmMFhKuxcv2dJ2T1tyZGRGCzAgLWZpfWxAICXlwPIHZYwjtaHS6KIRHYmoCAtbUVNZ+UQHuh/bt2WU9xdlvHO1rdLo2BEVi3gIC17vUz+vkEPlNVz81XXuXOBDw+7GxBDIfA2gUErLWvoPFPFbhs64UfVtV9U4sf8fz2NTztz3VfxTP0uCNOZbFLty+efrKq7Aq/GLkLEdiugIC13bU1s+sFetx6Ycj3E7bHWi9X1UNV9URV3TyZ6vl3i9pf366qpwLHvVtVf7qDR6bN/4tVdef69nEEAQIELhcQsHTHXgV6/HRgC06PVdVvDwhFx7jLctVGq69W1QNVdWsjDeWR4UYW0jQIHEtAwDqWvOseU6DHcNU8nt7AnZMe7wqO7TUha6yc8wgQ8FU5emB3Ar1uvbClX+ZbutP1UlV92ntZu/s5YcIEJgu4gzWZUIEVCfS69cKWwtXQdljTnS5bOQxdVccRIPC+gIClGfYk0NvWC3v/xX3Zna43q+r+Dhtzj0G4w2UwJALrEBCw1rFORpkR+ObJy+OZasOqvF1V/33FJ/2O8bL6sJEf96he35OzlcNx+8LVCaxGQMBazVIZaECg7cx+uqVBoNygElt4cX3QRGc4qNfHiLZymGGxlSSwNQEBa2sraj5XCbS9nJb845HSdO3LHiNOrzy9gvWdbqgCgc0KCFibXVoTu0BgyYDll+98LdjT40PrPN86q0xg1QIC1qqXz+APFFjiEeHeX1w/cElGH97T40OPgUcvoxMJbFdAwNru2prZhwWSL7mf/a7C819R48X1Zbqvl8eH7Z2sR6qq9YQ/BAgQeE9AwNIIexJIbtPw2ap6fk94K5nrsR4fevF9JQ1imASWEhCwlpJ2nR4EUhuNtseAj9rdu4clvXAMxwpZbTDeyeq2LQyMwLICAtay3q52fIHEV+V45+b463jdCNo6f6mqHrzuwBn+u5A1A6qSBNYmIGCtbcWM97zAdd97962qevHc3aYpdzj88lxPD7beeLmqbh1hyEL4EdBdkkBPAgJWT6thLIcKDP0k2UWf7BsTsoSrQ1eoj+PHrPXUkb9VVR/zGHkqo/MJrFdAwFrv2u195GN+aZ4PSFMC2t791zb/oWudnNe/VtUvJAuqRYDAegQErPWslZF+IDAmXJ2efT5kjXnEaC3WKdDW+q+q6pMLDv8fq+pXF7yeSxEg0ImAgNXJQhjGYAEvqQ+mcuAlAlMC+hjUr1bV58ac6BwCBNYrIGCtd+32OHLbLOxx1eeZ89Ihy0vv86yjqgS6FRCwul0aA7tAwEah2iIpsORWDvZOS66cWgRWICBgrWCRDPF9geRX3bTtGz7BdvcCS27lYPf/3bcbgD0JCFh7Wu31zzX5Zc3t+wPbbuz+EGgCSzwyFOr1GoEdCQhYO1rsDUz13fAc9H8YdOXl5n5kKNSvvEEMn8AhAn7BHKLl2GMLCFjHXoHtX/++qmrvS831FTt+5m6/h8yQwHsC/rFrhDUJfK+qHgoN2N2EEOQGyyS2ArmMxc/cDTaMKRG4SMA/dn2xFoH0OzLeh1nLyh9nnN+e4TsM2x3Ye44zHVclQGBpAQFraXHXGyOQDldtDD7RNWYl9nNO+3Th96vqRnjKfuaGQZUj0KuAf+y9roxxnQrM8bjGnkT6a4jAHL3nZ+4QeccQ2ICAf+wbWMQNTyG1c/t5Irtqb7hpwlPzwYowqHIE9iIgYO1lpdc5z+TO7acC57/seZ0yRr2UgIC1lLTrENiYgIC1sQXd2HSSO7c3GuFqYw2ywHQErAWQXYLAFgUErC2u6nbmlNy5/fWqeng7NGaykEByaxA9uNCiuQyBHgQErB5WwRguE3D3QG8cW6Bt5/HroUH8XVU9FaqlDAECnQsIWJ0v0M6HJ2DtvAE6mH7yPUBbg3SwoIZAYCkBAWspadcZI/BGVd0/5sQLzrFzewhyZ2VSn2S1NcjOGsd0CQhYeqBXgfTmonZu73Wl+x9XYj8sW4P0v85GSCAqIGBFORULCSR+oZ0fisczocXZaZkpgd+nV3faNKa9bwEBa9/r3+PsU49kzs7N45keV3p9YxoTsoSr9a2zEROICAhYEUZFggLJl4pPh+XxTHCBdl6q3V19tqoeucahhfpnqurOzr1Mn8BuBQSs3S59txO3uWi3S2NgJwLtLuvtky0Xnqiqmyd/3z5I8WpVtff9XrwbsN4hRoDAfgUErP2ufa8zT24u+mZVPdDrRI2LAAECBLYrIGBtd23XOjN7X6115YybAAECBN4XELA0Q28CAlZvK2I8BAgQIHCwgIB1MJkTZhZIPiK0uejMi6U8AQIECFwsIGDpjN4Eki+5t5eNf+PAF5LHvMB86DlzH9/bmhoPAQIEdicgYO1uybub8GVhIzHQl6rqyQM+Ut+ueehH8A/92P6h1zj0eNsCJDpHDQIECEwUELAmAjr9QoGhd2h+Z2CgGcP8VlXdGHPiAee8VlWPH3D8Eoe+UlXtOxxtH7CEtmsQIEDgEgEBS2scKnBdeHp94F2jJQLQoXPbw/E2wNzDKpsjAQJHFxCwjr4EXQ7gshDVwtPPVNW9XY7aoA4RcKfrEC3HEiBA4EABAetAsB0cPvSdoh1Q7HqK7nTtevlNngCBqQIC1lTBbZ0/5ststyVgNucFfFmxniBAgMAIAQFrBNrGTjl9HPjHVfXYxuZmOjkB37OXs1SJAIEdCAhYO1jkK6boceC+13/s7D0+HCvnPAIEdiMgYO1mqT80UY8D97v2qZl7fJiSVIcAgc0JCFibW9JBE/qLqvrDQUc6iMDVAkKWDiFAgMAFAgLW/triG1X1W/ubthnPKNC27/inqmpfTfRiVb0z47WUJkCAwCoEBKxVLFNskF+rqs/GqilE4MMC3s/SFQQIEKgqAWs/bfAPVfUr+5mumR5ZwKPDIy+AyxMgcFwBAeu4/ktdXbhaStp1zgoIWfqBAIHdCghY2196L7Rvf417nuHTVXWn5wEaGwECBOYQELDmUO2nZtvn6oV+hmMkOxT4cVX9fVV90wvwO1x9UyawYwEBa7uL33Zo/25VPbLdKR59Zq9V1eNHH8V6BuAF+PWslZESIDBRQMCaCNjx6Z+pquc6Ht/cQ2vv//xzVT07IGSe/uJvYzrk+Pboa+hu+GOvMXRMc3sm63s3K6mpFgECXQoIWF0uS2RQ7ZHMU5FK8xZ5q6puhC/R7ix9/KTm6XctNosn7j4yvXny95d9t96hx7dyh56TPv6BqroVNpy7nJA1t7D6BAgcVUDAOir/rBdvjwdPw8SsFxpZ/PSOzl/f/ZLp9r/fHFnnotPaXl/PB+utodTQO2k9zcUL8D2thrEQIBAVELCinF0Ve/eIo2nh6eWqemjgXaPk3ba3q6rd0dnjbuLX3Rnr7U5X65NHd7pWR/zn6dIECCwhIGAtoXyca8wdsFqQ+Z+TENVmeNkjtyGzT95ta1/b8vCQi+70mN7udO3xbuNOW8+0CexLQMDa7nq3OzgfnWF636mqP6uqv6yqH4Xqp8Ogvr56YX66qn735B29s++lhZbzoDLt+ws/cdAZDiZAgMAKBPwiWsEijRxiOrS0YXy1qj43cjxXnZYeq74+fJG+XFWfP/y0yWe0O5/tMaE/BAgQ2JSAX0SbWs6fmEw6tPzn3RfHf24mruQjQr+wxy/SsR4f+jk0fs2cSYBApwJ+sHW6MIFhJUPL6XDm+tRX8iV3j5ymNc/ZF+V/6cw7dtOqXn22n0Nz6qpNgMBRBPxgOwr7IhdNhpbTAc/1qa+/qapPhlS8NB2CPCkz96NDdxyz66UaAQKdCAhYnSzEDMOYayf3dIBJfqXPXAFwhuVZVck5Q5Y7jqtqBYMlQGCogIA1VGp9x7XgkvqU39nZt08R/nyQIxkEX6qqTwXHptQHAnO9n5UO7NaMAAECXQgIWF0sw2yD+N5M79C0UPT10KiTjzLdDQktyiVlTt/Patsq/FpV3TPxcu44TgR0OgEC/QoIWP2uTWJkyfBydjw/rqo/CIWs5Mv43udJdM2wGu2O1gvDDr30qLk+NDFxWE4nQIDAdAEBa7phzxWSj98ummfiC3vT20no6eU6csq7WYneWW6mrkSAAIEDBfwyOhBsZYcnXyC/bOqvVNWTE75PTsBaWVOdG+6YkCVcrXvNjZ4AgQECAtYApJUfkniUcx3BD6rqi3d35L5z3YEX/HePCEegdXbK0Bfg2ztXz4zsk86mbDgECBC4WkDA2keHfLuqbi0w1TF3Jl6rql8Mje1fqurxUC1lDhM4u0Hp2e83nPIl4IeNwNEECBDoSEDA6mgxZhxK++X3/aq6MeM1TksfGrIErAUWxSUIECBAYFkBAWtZ72NebYlHhafzO2QbB48Ij9kVrk2AAAECswgIWLOwdlv036vqsQVGd8g2Dl5yX2BBXIIAAQIElhUQsJb1PvbV5t624fz8hjwuFLCO3RWuT4AAAQJxAQErTtp1wSW2bTgPcN02Dsnd5m002nX7GRwBAgT2IyBg7WetT2e65LtYp9e8bBuHFvjeqKp7Q8vgq3JCkMoQIECAwDQBAWua31rPHrM5ZGKub1ZV2zKiBaEXq+p2VT2XKHxSwxcHBzGVIkCAAIHxAgLWeLu1n3mskHXq1jad/NHdTScfDUG+XVUPTNhRPjQMZQgQIECAQJWAte8u+P2q+lpV3bMBhter6uENzMMUCBAgQGADAgLWBhZx4hRayHp+Yo1eTtfPvayEcRAgQGDnAn4h7bwBTqZ/7MeFqVXQzylJdQgQIEBgkoBfSJP4NnXy2kOWLRo21Y4mQ4AAgXULCFjrXr/06NsWDl+qqgfThReoZ4uGBZBdggABAgSGCQhYw5z2dFTbm+rlqrq1sknbomFlC2a4BAgQ2LKAgLXl1Z02tzU9Mmzffdg2K31n2pSdTYAAAQIEMgICVsZxq1XWso3Da1X18a0ugnkRIECAwPoEBKz1rdnSI17DNg4eDy7dFa5HgAABAlcKCFgaZIhAz48L7eA+ZAUdQ4AAAQKLCghYi3Kv+mK9hqyXqupTq5Y1eAIECBDYnICAtbklnXVCvW3j8L9VdZ+X22ddc8UJECBAYISAgDUCbeen9LSNg7tXO29G0ydAgECvAgJWryvT/7iO/cjwrar6mLtX/TeKERIgQGCPAgLWHlc9N+f2yPDZqnokV3Jwpaer6s7gox1IgAABAgQWFBCwFsTe6KXaI8PbVfVUVf1yVd2/wDy/UlVfWOA6LkGAAAECBEYJCFij2Jx0hUC7q/XnVXVjJiXhaiZYZQkQIEAgJyBg5SxV+kBgjhfh2ztXf+SxoDYjQIAAgTUICFhrWKX1jjHxjlb7fsG/rapPe6F9vY1g5AQIENibgIC1txVffr5n39F6oqpungyh7WH10ZP//25Vne3FH1bVv1XVc1X1dcFq+UVzRQIECBCYJiBgTfNzNgECBAgQIEDgQwIClqYgQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBb4P/WXpq9IIZ9tAAAAAElFTkSuQmCC\"",
            "creator": {
                "userId": 6,
                "nickname": "Adolfo",
                "creationDate": "2024-04-25",
                "status": "OFFLINE",
                "persistent": null,
                "email": null,
                "password": null,
                "avatarId": 4,
                "role": "player",
                "token": "888c3a57-eb4e-4b26-8724-b3efdb1cfbb2",
                "gameRoom": null
            },
            "creationDateTime": "2024-04-25T13:09:43.461151",
            "gameSessionId": 1,
            "assignedTo": 3,
            "round": 2,
            "previousTextPrompt": 1,
            "nextTextPrompt": 3
        },
        {
            "textPromptId": 3,
            "content": "adsfasdf",
            "creator": {
                "userId": 3,
                "nickname": "Greta",
                "creationDate": "2024-04-25",
                "status": "OFFLINE",
                "persistent": null,
                "email": null,
                "password": null,
                "avatarId": 1,
                "role": "admin",
                "token": "79e902ba-5a46-4329-b2b0-1549eb46766d",
                "gameRoom": null
            },
            "gameSession": {
                "gameSessionId": 1,
                "creationDate": "2024-04-25",
                "token": "0d529e1d-2d4c-4d41-b43e-f57b53c307a9",
                "status": "IN_PLAY",
                "usersInSession": [
                    3,
                    6
                ],
                "roundCounter": 8,
                "currentIndex": 0,
                "gameLoopStatus": "PRESENTATION"
            },
            "assignedTo": 6,
            "previousDrawingId": 2,
            "nextDrawingId": 4,
            "round": 3
        },
        {
            "drawingId": 4,
            "encodedImage": "\"iVBORw0KGgoAAAANSUhEUgAAAlgAAAGQCAYAAAByNR6YAAAAAXNSR0IArs4c6QAAIABJREFUeF7t3T2vNddZBuAnMSEmlkI+EC7swukoEMI9SHZBgeT8gyAUwmdCFCEKKFymCEUEiJAPYqcgdCkxorCELSFqI/6AIxEXCAghwiGW7YR3yDn2eZ2zz56Pe82eNXNFQkS8M8+sda3nnHMzM3vtd5X/ECBAgAABAgQIRAXeFa2mGAECBAgQIECAQAlYmoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQGDLAj9RVZ+oqqeq6vGqeuRqsN+/+t8PXv3vV6rqpap6rqqerao3tjwpYyNAYP8CAtb+19gMCWxN4FRoGkLSt68G+6EbYWrq+F+rqm9U1ccFral0jidAICUgYKUk1SFAYIzAb1bVZ6vq4TEHLzzme1X1map6ZmEdpxMgQGCygIA1mcwJBAicETh1h+rVqnroAnpfqKpPX+C6LkmAwIEFBKwDL76pE2ggsOYdqinDF7KmaDmWAIHFAgLWYkIFCBxS4NRdqi1j/JbHhVteHmMjsC8BAWtf62k2BNYQ2OpdqnNzH97J+mkvvp9j8u8ECCQEBKyEohoEjiPwF1X1+x1P98WqerLj8Rs6AQKdCAhYnSyUYRLYgEDv4eqa0KPCDTSTIRDYu4CAtfcVNj8C0wV6fL9qyiw9Kpyi5VgCBGYJCFiz2JxEYLcCvb5fNXVBPCqcKuZ4AgQmCQhYk7gcTGDXAnt5BDh2kTwqHCvlOAIEJgsIWJPJnEBglwJHC1fDIv7bvW0bHvWpwl32s0kRuLiAgHXxJTAAAhcXGB4LfvXio7jMAH63qr5ymUu7KgECexYQsPa8uuZG4EcCd3258j9X1S9X1fsPivXNqvrIQedu2gQINBQQsBriKk1gAwJHeWl9CbV3sZboOZcAgVsFBCyNQWC/Akd8r2rOanoXa46acwgQuFNAwNIgBPYpIFxNW1fvYk3zcjQBAmcEBCwtQmB/Akd+aX3uaj5XVR+de7LzCBAg8E4BAUtPEOhT4K4X13+mqt7b57QuNupXrrZsuNgAXJgAgX0JCFj7Wk+zOYbAnl5cf7WqHrpatiHkfPvqv3/o3tYRj9z4v79UVcNdpmer6vmqeqLBUvt92ABVSQJHFfAL5agrb969Cuzl3arhxfKn7901embGQgx37/67qt4349y7TvH7MAyqHIEjC/iFcuTVN/feBHoPV8Mdqpt3ot5YsAAt3jOzXcOCBXEqAQL3CwhYOoJAHwItAkXrmS+5SzVmbC9X1WNjDhx5jO0aRkI5jACB8wIC1nkjRxC4tMDwSOxbVfXwpQcy4vrJu1TnLvc7VfXlcwdN/HfbNUwEczgBArcLCFg6g8D2BVoEieSsv1BVn04WHFmrRfC0XcNIfIcRIHC3gIClQwhsS+DU9gvbGuXbo7lUuLoeQfrRqe0attppxkWgMwEBq7MFM9xdC/S0/ULr96umLPQPpxw84li/F0cgOYQAAXew9ACBHgS29gnB71bVP1bVL96xH9WSTwEm10TASmqqRYBARMD/pxZhVITAIoGthathMj1tWTB8AOB6U9JFC3F1ck9zT8xXDQIEGggIWA1QlSQwQSD9DtGES5889NLvVU2dw99W1VNTT7rjeNs1BDGVInBUAQHrqCtv3lsQaPEpuKXz6i1cDfNt8SlL2zUs7STnEzi4gIB18AYw/YsKtAgGcye0pZfWp86hRVC1XcPUVXA8AQL3CQhYGoLA5QTSj7bOzeS1qvqPDl5aPzeP2/49/ajVdg1zVsE5BAi8JSBgaQYC7QVO7W31ZlU90P7yb11h7y9v+zThis3kUgQI3C0gYOkQAm0FtrK3VY/vVk1dGQFrqpjjCRBoJiBgNaNVmEBtZfuFI4Srod2S2zV4ROgHmACBRQIC1iI+JxM4KbCFcNXzi+tzWiv5TpuX3OesgHMIEHhLQMDSDATyAukXrqeMcLjz8lJVDQHh2araym7rU+Yw99hha4UvzT35Hee9WFVPhmopQ4DAAQUErAMuuik3FWixZcCYAdu3qSptv/cPBYzpK8cQIDBTQMCaCec0AicELrG3lZ3H316M5N1Drn7MCRCYLSBgzaZz4sEFTm298P2qenBlG3da7gd/oaqeCK2BO4MhSGUIHE1AwDraiptvQmArWy8McznKJwSnrJuX3adoOZYAgSYCAlYTVkV3LLCFTwde8wpXtzea7Rp2/ANoagR6ERCwelkp49yCwFbC1dG2X5i69jYcnSrmeAIE4gICVpxUwZ0KJF+eHkt086t0jrz9wliv6+MErKlijidAIC4gYMVJFdyhQPrj/2OJbHY5Vur+4zwinOfmLAIEggICVhBTqd0InPqE4NoT9Am2eeLJl9y/WVUfmTcMZxEgcGQBAevIq2/utwls5ROC9mCa35/pvchsgzF/LZxJ4LACAtZhl97EbxHYykvsw9D8UZ/foulHusLu/LVwJoHDCghYh116E3+HwJbCle0Xlrdn+kMJHtcuXxMVCBxKQMA61HKb7AmB9B/jJdDC1RK9+899uaoeC5XzgYMQpDIEjiIgYB1lpc3zlED6cdJcaXtbzZU7fZ5PE+ZNVSRAYKSAgDUSymG7FUi/EH0O6uZ3Fdrb6pzWsn+3H9YyP2cTILBAQMBagOfUXQgkP9I/BsS7PGOUMscIWBlHVQgQmCEgYM1Ac8quBJKPkc7B7O3TaKf2C/tOVb1WVe+tqg9coVzibl1ybYfxP3pugf07AQIErgUELL1wRIGbweCpFQF63XrhVJD6QVW9e4bfEL7+d4Xwlbw76SX3GQvtFAJHFhCwjrz6x5z7pTYS7fXTgWt7JcNX8v26F6vqyWP+yJg1AQJzBASsOWrO6VXgUntd9RSubt6tGgLFQxta7KmftEx/QrTXO5AbWkJDIXAcAQHrOGt99JleIlxNDQSXXqO171Ytne+Y97qSe5zt7R26pf7OJ0DgDgEBS3scQSD5R/ac15g/+udqXOLfLxFAk/O8K8y+UFVPhC7mU6AhSGUI7F1AwNr7Cptf+jHRKdGe7270Hq5ursltj2O97O73AAECqwsIWKuTu+DKAskXne8aem/v51y/a/XJqvqFldek9eVevfHu2HBH8cNV9WDoorZrCEEqQ2DvAgLW3lfY/JJ3L05p9vQS+zCH3t612loX+725tRUxHgIbFPCLYoOLYkiLBW5+Eu5Xq+qBxRVPF+gtXO3pcWDDZb2ztN+bl5J3XQIdCfhF0dFiGeoogbXuzvT2CcEBT7ga1UJ3HuQR4XJDFQgcQkDAOsQyH2aSawSIYUfv4X++VlWvdyS75icpO2KZPFQ7uk8mcwKBYwoIWMdc9z3Oeo1w1ePdi+Fx6fAC/p9efTfgHtd+zTnZpmFNbdci0LGAgNXx4hn6WwJr3Z3p7e7FWo9Lj9SKw6dS/+pIEzZXAgTmCQhY89yctR2Btfa5Gmbc092LNe7obacL1htJz/udrafkSgQIlIClCXoXWGufq57+sApXbbu6p6DdVkJ1AgROCghYmqN3gTX2uRqMetlIdK3Hpb33zZLx9/aoeMlcnUuAwEwBAWsmnNM2ITA8Hvz3qvpA49H0stfVmo9LG5Nvuvx3quqDmx6hwREgcHEBAeviS2AAMwXWeoG7l3A1MH69qj4209Np0wR66otpM3M0AQIRAQErwqjIygJrvGPU20aia5jctcw/qKp3Xx0w3OF57WpbiOu7i8P/7ad2tlWEkLXyD77LEehJQMDqabWMdRBoGSTerKq/v9pI9NmqeqMT8pYmdxEMX6r8wgSvm19h9HhVPXIjkPUavnp5N6+TVjZMAvsRELD2s5ZHmEnrF7h7fHm5tcltfdXi7t6p8NVDXw8b0L40IWj2MCdjJEBgoYCAtRDQ6asJrPECd28fv1/D5OYC/0tVfbGq1ry7t9a7dqlGbhE+U2NThwCBFQUErBWxXWqRQOv9rnra5+oasrXJzQW75PtGp+5uDY8oH1rUVe1OvqRXu1mpTIDAaAEBazSVAy8s0Hq/qx7fpWltcr3kWw4Ll3r/bMyPw5bdxozfMQQILBAQsBbgOXVVgf9quN9Vr38IW5oMi9vL464tP0bsMbiv+oPtYgT2KiBg7XVl9zWvlncpeg1XLU2GLRb+4N6n/L7a0Scpt/qSfI+W+/rtYTYELiQgYF0I3mVHC7QKEr3cnbkNqpXJ9bX2cteltdPoJu7obuCUOTmWAIE7BAQs7bFlgVZbEAybXv5sVb2+5cmfGFsrk+vL9XpH79RSbilkDWPcm2+HP0KGTGAdAQFrHWdXmS7QcguCHve7GgRbmuz5j//W3tESsqb/PnAGge4EBKzuluwwA265BUFv+11dL3rL7xr8m6r6tR131/U7Wn9WVQ9uYJ57eQy7AUpDILBNAQFrm+tiVFWttiDocb+roR9aPurq1WTOz0mrvpo6luG7G4evZRrGs+bGrVPH6XgCBGYKCFgz4ZzWXOBbN76rLnmxHu8ctAxXg22PJnN7ouWd0blj6vkDF3Pn7DwCuxcQsHa/xN1O8IcNRt7juy9eas82Quv32JaMtsf+XDJf5xLYtYCAtevl7XZyLe7Y9PjHq3UY6NEk0dStQ+uSMR51TZaYOZfAJgUErE0uy6EH1eKP37Atwwc7VG35OKtXk9QytgjxqbEd6ZFtykwdApsTELA2tySHHlCrOza9bsvQ8oXsXk2SPyAtHkMnxvfdex9q+HBHu+gn5qwGgd0JCFi7W9KuJ9Tqjk2v2zK0etF/aJJeTZINvtWANczxxap6MjlZtQgQWFdAwFrX29XuFmhxx6bnLQhaBYCeTZI/Qy0DbGKc3sdKKKpB4EICAtaF4F32VoEWf/B6fZ9leFza6qt8ejVJ/9i0CPTpMVqrtKh6BFYSELBWgnaZUQLpOzY93wFo9bi0Z5NRTTThoFbGE4Zw9lB3G88SOYDANgUErG2uyxFH1eKOTc/9/XJVPRZuBOHqftBWH6oIL1vt/WuM0l7qEdiEQM9/gDYBaBAxgfTdhFeq6tHY6NYt1GILAX+kb1/DFtuCtOgW4biFqpoEGgoIWA1xlZ4kkH4fptdtCFr9wX+Pj/2f7McWgXZS8488WMgaCeUwAlsQELC2sArGMAi0eMH9nbLD5pr/tOEv2G35yMrP+t0/Z+n3/1r9VHvpvZWsugTCAn7phkGVmy2w9h+4LX7Bbvox6fVi9Py4dHZDTTxxjYA/cUi3Hm4T0oSiGgRWEBCwVkB2iVECawes60F9sao+NWqE7Q9q8WL7MOpeH5e2F3/7CulH1C3HbhPSlrpqEwgJCFghSGUWC7xRVQ8srjKvwH/eez/p6XsvxT9zwfeUWr17NYjYtf18XwxGXzp/2GaO8D7WZpbCQAjcLiBg6YytCFzqDtbN+V/qsWHLd6/sozSuw1uuwbgRTD/K+1jTzZxBYDUBAWs1ahc6I7CFgHU9xG9W1Z+seEer1btXw3z8ER7/o9fyLuL4UYw/Ungeb+VIAqsLCFirk7vgCYFLPiI8tShr3dFq9f6Px0jTf9x62bLhemYe/05fY2cQWEVAwFqF2UVGCGzpDtY7hzvc0fpcVT3b6B2tV6vqfSOMphwyjPkjU05w7FsC/1NVD3Xi4QMMnSyUYR5PQMA63ppvdcZbDljXZi3uaP1lVX2ywaK4szEftdUdxfkjOn3msLfbB1sUVpMAgWUCAtYyP2fnBHrZh2iYcerRW6vHUd7NWdaXLd+JWzay28+2S38LVTUJLBQQsBYCOj0m0NNdg2HSSx8btnyh2ovty9qyt08Uulu5bL2dTaCJgIDVhFXRGQK93TW4nuKcx4Yt/4B792pG891ySssAnBnh21X+rqqeShdVjwCBZQIC1jI/Z+cEhtAxbPj5/lzJVStNeWz4e1U17CDf4j/uZuRUWz3CzY3wR5W8h5UWVY9AQEDACiAqERP47ar6Sqza+oWGrzD5lTOfNBzujHy54a713sfJrnsvIcvv8uy6q0ZgsYAfysWECoQF/qGqngzXXLPc8GW8f3i1SenN6w536J6vqicaDsadjDa4X6+qj7UpHavqd3mMUiECGQE/lBlHVbIC/3ovoDyaLXmxam82vFv1zknZE6nNMrd8Zy41Yr/LU5LqEAgJ+KEMQSoTF9hTyIrjnCjo/at20lt/6d3v8nZrrzKBWQJ+KGexOWklgd4fF67E9P+XsfdVe+2tvo81bNL7k42+ZaC9qisQ2KmAgLXThd3RtIYX3//83lfVPLijObWYir2vWqj+eM2thqw524WsI+YqBA4qIGAddOE7m/bwDswQIIbtDX6uqoZPyvnP2wJTtojgtlxgeFz4+Y1uKaIXlq+vCgQiAgJWhFGRDQoMfwQ/W1UPb3BsySEN+2l9KllQrVECwx3V4a7RFvdtG7NdyKhJOogAgfkCAtZ8O2duX2C48/WJqy9T/vmqevf2hzxphH9dVb8+6QwHJwW2/OL7qe1CkvNXiwCBOwQELO1xFIHrsPXHVfXYDibtK3G2sYhbfSfrWufVqnqhqoYtPJ71Ivw2msYojiEgYB1jnc3yfoE9PD60JcN2unrrIetayovw2+kZIzmAgIB1gEU2xVsFhjtaQ9D6ow7vaNmSYXtN3VNov76rNXxJ9DPuam2vmYxoHwIC1j7W0SyWCfT0x3GYqS0Zlq13q7OvH0M/VVW/VFUfaHWhYF13tYKYShG4KSBg6QcCPxLo5R0tH8Pvp2N7eXQ4iHpXq5++MtJOBASsThbKMFcV2OofRuFq1TaIXGyrvTRmcq9U1UtekB9D5RgCPy4gYOkKArcLbGkzye9V1Weu3pexXv0J9PYI+jZhjxL76zsjvrCAgHXhBXD5TQsMjw2fr6onLjhKm0ZeED946V4eQZ+b8rA9yOds+XCOyb8TqBKwdAGB8wKXeMzjrtX5den1iEv0U9rKHa20qHq7ExCwdrekJtRIYM3HPO5aNVrEDZVds59aTtt7gS111e5aQMDqevkMfmWB1o953LVaeUEvfLmb2zo8XlWPXHg8cy8vZM2Vc96uBQSsXS+vyTUUSN6BeK2qvlFVH7fpY8MV66N0sq/WnLG92dbUdq0uBASsLpbJIDcqcOoOxJtV9cDVmE/9dx+B3+iibmBYre+Utpiibxdooapm1wICVtfLZ/AECOxcYEvbhZyj9v2Y54T8+6EEBKxDLbfJEiDQocAWtgsZw/ZcVX10zIGOIXAEAQHrCKtsjgQI7EFg69s7DI+9H90DtDkQSAgIWAlFNQgQILCOwNZfgvc3ZZ0+cJUOBPwwdLBIhkiAAIEbAjc/XPFkVT20IR1/Uza0GIZyWQE/DJf1d3UCBAgsFdjKXS2PCJeupPN3JSBg7Wo5TYYAgYMKbOGulpfcD9p8pn27gIClMwgQILA/gUvc1bJNw/76yIwWCAhYC/CcSoAAgQ0LrHlXy0ajG24EQ7uMgIB1GXdXJUCAwNoCLe9q+aqctVfT9TYvIGBtfokMkAABAjGBFl8w7cueY8uj0J4EBKw9raa5ECBAYLrAku8+FK6mezvjIAIC1kEW2jQJECAwQmDsY8Thnaun7+3c/syImg4hcEgBAeuQy27SBAgQOCnwnqr6jap6qqoer6pHro4c9rl6qaqG7Ri+VlWvMyRA4LSAgKU7CBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKXr8UP+AAACvklEQVQHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBAQsPQAAQIECBAgQCAsIGCFQZUjQIAAAQIECAhYeoAAAQIECBAgEBYQsMKgyhEgQIAAAQIEBCw9QIAAAQIECBAICwhYYVDlCBAgQIAAAQIClh4gQIAAAQIECIQFBKwwqHIECBAgQIAAAQFLDxAgQIAAAQIEwgICVhhUOQIECBAgQICAgKUHCBAgQIAAAQJhAQErDKocAQIECBAgQEDA0gMECBAgQIAAgbCAgBUGVY4AAQIECBAgIGDpAQIECBAgQIBAWEDACoMqR4AAAQIECBD4P7GkIb7/Hd5oAAAAAElFTkSuQmCC\"",
            "creator": {
                "userId": 6,
                "nickname": "Adolfo",
                "creationDate": "2024-04-25",
                "status": "OFFLINE",
                "persistent": null,
                "email": null,
                "password": null,
                "avatarId": 4,
                "role": "player",
                "token": "888c3a57-eb4e-4b26-8724-b3efdb1cfbb2",
                "gameRoom": null
            },
            "creationDateTime": "2024-04-25T13:09:53.223096",
            "gameSessionId": 1,
            "assignedTo": 3,
            "round": 4,
            "previousTextPrompt": 3,
            "nextTextPrompt": 5
        },
        {
            "textPromptId": 5,
            "content": "gagaga",
            "creator": {
                "userId": 3,
                "nickname": "Greta",
                "creationDate": "2024-04-25",
                "status": "OFFLINE",
                "persistent": null,
                "email": null,
                "password": null,
                "avatarId": 1,
                "role": "admin",
                "token": "79e902ba-5a46-4329-b2b0-1549eb46766d",
                "gameRoom": null
            },
            "gameSession": {
                "gameSessionId": 1,
                "creationDate": "2024-04-25",
                "token": "0d529e1d-2d4c-4d41-b43e-f57b53c307a9",
                "status": "IN_PLAY",
                "usersInSession": [
                    3,
                    6
                ],
                "roundCounter": 8,
                "currentIndex": 0,
                "gameLoopStatus": "PRESENTATION"
            },
            "assignedTo": 6,
            "previousDrawingId": 4,
            "nextDrawingId": 6,
            "round": 5
        },
        {
            "drawingId": 6,
            "encodedImage": "\"iVBORw0KGgoAAAANSUhEUgAAAlgAAAGQCAYAAAByNR6YAAAAAXNSR0IArs4c6QAAIABJREFUeF7t3b/PJVd5B/AHgwOCCBlRLNJuAX2C5DopoEiBWBfpoUiMY0C2lCjtporbKJGwYhvvkgLaKIWxKFJAk9oS/AFQYAkKBEKBhHixswPvxa/f3ffeuTPPmfNjPm535jnnfM55r7+6c+6Z94X/CBAgQIAAAQIEUgXel1pNMQIECBAgQIAAgRCwLAICBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAAAECBAgkCwhYyaDKESBAgAABAgQELGuAAAECBAgQIJAsIGAlgypHgAABAgQIEBCwrAECBAgQIECAQLKAgJUMqhwBAgQIECBAQMCyBggQIECAAAECyQICVjKocgQIECBAgAABAcsaIECAQBsCH4iIpyPiqYj4s4h44ppu/SIi/isiXouIexFxv43u6wUBApcFBCzrgQABAtsLHMLU7Yh4MiJuLuzCTx8ErDsRcXfh/W4jQKCQgIBVCFZZAgQIXCPwpYh4ISJuJAq9GBHPJ9ZTigCBlQIC1kpAtxMgQOCEwOVvqz4bER8pJCZkFYJVlsASAQFriZp7CBAgME+gxLdVx1p+xuPCeRPjKgKlBQSs0sLqEyCwV4GvRcRzGw9+2pN1y8b3jdU1R+ARAgKWZUGAAIEcga0eBZ7q7Zcj4pVTF/l3AgTKCghYZX1VJ0BgHwJbPwo8pvrti6Me9iFvlAQaFRCwGp0Y3SJAoBuBGo8Cj+G8efGYsBtAHSUwooCANeKsGhMBAlsJtBauDuP22b7VCtAOgWsE/BFaGgQIEJgnkHU46LzW1l3ls32dn7sJrBbwR7iaUAECBHYg0NIeq1Pcb0fE+09d5N8JECgrIGCV9VWdAIH+BVp9DHhM9nFHNfS/8IygbwEBq+/503sCBMoK9BiuJhFHNZRdF6oTOCkgYJ0kcgEBAjsVmB4Lvtrp2B3V0OnE6fY4AgLWOHNpJAQIrBc4bGR/KiI+FxGPrS9ZpYKjGqqwa5TAuwICltVAgACB3wv0tJF9zpz5fJ+j5BoChQT8ARaCVZYAga4Eet1rdQzZ53tXS1BnRxPwBzjajBoPAQLnCowYrjwiPHcVuJ5AsoCAlQyqHAECXQn0vJH9GPQPIuLTXc2EzhIYTEDAGmxCDYcAgVkC02b2ZyLinyPig7Pu6OsiAauv+dLbAQUErAEn1ZAIEDgq0OJm9p9eBL0nkubOI8IkSGUILBUQsJbKuY8AgR4FWtpv9auI+G5ETGdW3YuIt5JBfb4ngypH4BwBf4DnaLmWAIGeBVoKVy9GxPNXMN9JxvX5ngyqHIFzBPwBnqPlWgIEehVoZTP79CjwTkTcvQKZHf48Iux1per3MAIC1jBTaSAECFwRaOVU9insvHHpUeD9K/0sEf68KsefA4HKAgJW5QnQPAECRQRa2Mj+qMeAVwc7hcAfR8SNZAUve04GVY7AuQIC1rliridAoHWB7MdtS8Y7J1xNdZ+NiJeXNHDknukx5K0HjyKvflOW3IxyBAgcExCwrA8CBEYSqB2urttjdZ3xaxFxO3kCpvO9ru7xSm5COQIETgkIWKeE/DsBAr0I/E1EvFKhs29HxHciYgpL03EL53xzND0evJnY57nfnCU2qRQBAo8SELCsCwIERhCYwtVLEfFYhcGs+cbI0QwVJkyTBLYQELC2UNYGAQIlBWo+Flz7jZGAVXJlqE2gooCAVRFf0wQIrBboOVxNg898ROjsq9XLSQECeQICVp6lSgQIbCtQ4vyoOSM4dyP7sZqZm9ydfTVn9lxDYCMBAWsjaM0QIJAqUOr8qGOd/E1E/N2DTemvnrmR/VjN6V2En0mScfZVEqQyBDIEBKwMRTUIENha4JsR8YWNG12zmf1RXc18vOnsq40Xg+YInBIQsE4J+XcCBFoTyAwmc8e2djP71XayH29mh7+5Lq4jQOAaAQHL0iBAoCeBEcJV9uPN7PDX03rQVwLNCghYzU6NjhEgcEUg+1ufU8CZm9kvt5X5epzvRcRnTw3EvxMgsL2AgLW9uRYJEDhfIPtbn+t6sOZU9rmj8svBuVKuI9CxgIDV8eTpOoEdCUy/kJtOai/93xZ7mZx9VXoW1SfQgICA1cAk6AIBAicFfhgRnzx51boLttrL5PT2dfPkbgJdCAhYXUyTThLYtcAWG9u3ClfTRApYu17OBr8XAQFrLzNtnAT6FCi9sX3ac/WViPj6hjweEW6IrSkCtQQErFry2iVA4JTAFhvbp1/0bRmupjFPr7T5/KnBz/x3r8eZCeUyAlsLCFhbi2uPAIG5AqU3tm/5WPAw5ukbuX+KiI/ORThxndfjJEEqQyBbQMDKFlWPAIEsgZIb22uEq+y9ZF6Pk7XS1CFQQEDAKoCqJAECqwVK7r36VkR8cXUPzyuQHa6m1rc4UuK8UbqaAIE/CAhYFgMBAq0JlNx7VeNbnxJhscY3cK2tE/0h0LSAgNX09OgcgV0KlNx7tfW3PiXConC1yz8Lg+5NQMDqbcb0l8D4ApmvkrmsVSOYZL538JcR8fcRcXf8JWCEBPoXELD6n0MjIDCaQOY5UQebH0XEpypAZYbF1yPidoUxaJIAgQUCAtYCNLcQIFBUIPuk86mztY4zyAyLbz749upWUXnFCRBIExCw0igVIkAgSSA7YNXY2H6gyB6Lz+ykRaYMgdIC/lhLC6tPgMC5Av8TER8696Yj12+9sf1yVwSsxIlUikBPAgJWT7OlrwT2IZAZsH4bEdMv+Wr95xFhLXntEqgsIGBVngDNEyDwkMBI3/pkbnL33kF/LAQ6EhCwOposXSWwE4GRAlbmMQ21NurvZNkZJoFcAQEr11M1AgTWC/w8Ip5YX+Z3FX4RER9LqnVOmemx5NMR8VREfC4iHjvn5kdcW3Oj/squu53APgUErH3Ou1ETaFngJxFxI6mDUzD5RFKtuWWmV+O8kDiGqd2aG/Xnjtt1BAhcEhCwLAcCBFoT6PkbrBIvda5xAn1ra0J/CHQnIGB1N2U6TGB4gV73YAlXwy9NAyQwX0DAmm/lSgIEthHIDliPR8T9wl2fHgu+mtjG9GjzjvcOJooqRWBjAQFrY3DNESBwUiDz7KipsdK/vps2tE99Xrtv7O2I+E5ETEc73NsgFJ6cCBcQILBcQMBabudOAgTKCGSeHTX1sPT5UY5iKLMOVCXQtYCA1fX06TyBIQWmb5xeShxZ6ZckZwbC0mEwkVUpAgSOCQhY1gcBAq0JTI/c3kruVMnPusxHmqXDYDKrcgQIXCdQ8kOHOgECBJYK9LTRPbuvPpeXrhr3EWhIwB9yQ5OhKwQI/EEg81uhqWjJje4CloVLgMBDAgKWRUGAQIsCmfuapvGV3NuUGQY9ImxxNeoTgQUCAtYCNLcQIFBcIPOXeVNnSwaXzDBYMggWnzQNECDwroCAZTUQINCiQE8b3TN/9VjyUWaL86xPBIYVELCGnVoDI9C9QPbepqwT3afw93RE3I6IJx+c4H4zSXo6vf2WA0aTNJUhUFlAwKo8AZonQOBagcy9TVMjGd8OTa/EeSHh1PZHDfoZr8bx10BgHAEBa5y5NBICowlk7m2abH4UEZ9agVTiZc6H7rwYEc+v6JtbCRBoTEDAamxCdIcAgT8IZG90nwov/ZZIuLIwCRA4S0DAOovLxQQIbChQYqP7LyPi42fuc5oeC75aYNzTnqs7HgsWkFWSQAMCAlYDk6ALBAhcK5C90X1q6HsR8dmZ5lPIm/aC3Zh5/anLpuMi3oiI1y+C1f1TN/h3AgT6FBCw+pw3vSawF4Hsje4Ht7l7nhzBsJeVZpwEkgUErGRQ5QgQSBXI3uh+uXNz9mNltu8Q0dSloRiBtgUErLbnR+8I7F2gxEb3g+mcc6cyv0EreZr83teJ8RNoTkDAam5KdIgAgUsC2XugruJ+KyK+eEQ8ew+Yz1zLm8BOBPyx72SiDZNAxwKlfsV3IDm2H0vA6njh6DqBmgICVk19bRMgMFfghxHxybkXL7juupDlEeECTLcQIBAhYFkFBAj0IFByL9Zh/NPjwr+6ckaWTe49rA59JNCggIDV4KToEgECDwmU3ot1aPDq4Z+ZwS7jXYiWBgECnQgIWJ1MlG4SIBCl92JdJj48MswKdnN+sWiKCRAYSEDAGmgyDYXADgRKvhPwOr5fR8SHV9rOOXNrZRNuJ0CgJQEBq6XZ0BcCBOYIfPfB624+M+fCRq6Ze2p8I93VDQIEMgQErAxFNQgQ2FJgemz3s4j46JaNLmxLuFoI5zYCvQsIWL3PoP4T2KfAlvuxlghf3Sy/pIZ7CBDoWEDA6njydJ3AzgVq7Me6Sn55f9b0Kpw3ImJ65+C9K8c97HyqDJ/A/gQErP3NuRETGEmghZDl26qRVpSxEEgSELCSIJUhQKCawDcj4gvVWn+3YfutGpgEXSDQioCA1cpM6AcBAksFss6qWtr+5fuErAxFNQgMICBgDTCJhkCAwKaHkJ7idubVKSH/TmAHAgLWDibZEAnsRKCF/ViXqW1638nCM0wCjxIQsKwLAgRGEmgtZB1sbYQfaZUZC4EZAgLWDCSXECDQlcB0RtYLEXGjwV7bo9XgpOgSgRICAlYJVTUJEKgtMG18/7dGfl141ULIqr06tE9gAwEBawNkTRAgUE2g1UeGBxD7tKotDQ0TKCsgYJX1VZ0AgfoCrYesg5B9WvXXih4QSBMQsNIoFSJAoDGB6THhtB/r8xHx5xHxRGP9u647HiF2MlG6SeCYgIBlfRAgMKJAyxvd53gLWXOUXEOgYQEBq+HJ0TUCBBYJ9PJI8NTgvh8RH4+ImxcX2q91Ssy/E2hIQMBqaDJ0hQCB1QKjhKtTEPZrnRLy7wQqCwhYlSdA8wQIpAlMjwVfXVnt/yLij1bW2PJ2jxK31NYWgTMEBKwzsFxKgECzAlkvfJ6+Gfr3iPhqsyN9uGNCVkeTpav7ERCw9jPXRkpgZIFnI+LlpAF+OSL+JCKeS6q3RRkvmN5CWRsEzhAQsM7AcikBAs0KvBYRt5N69+2IeOriiIdWX7lzdajTN2+3IuJ+koEyBAisFBCwVgK6nQCBJgR+fOnXdms7NP1abwor03+PR8RfX4S3JxPbWNvHR90/ffP2SonCahIgcL6AgHW+mTsIEGhP4J3kLh37bMzYTJ/c3d+VO3zzVqK2mgQInCkgYJ0J5nICBJoU2DJgTQAtHgdx+Zu3JidJpwjsSUDA2tNsGyuBcQVKPSI8JtZiyPKZPu4aN7LOBPwxdjZhukuAwCMFSmxyn0Pd2it5fKbPmTXXENhAwB/jBsiaIECguED2MQ3nbBafzuB6uoGN8B4RFl9mGiAwX0DAmm/lSgIE2hXIPGg067iDrR8h2uTe7vrUsx0KCFg7nHRDJtCRwHXfDj3qxccZv+7LPrBzy5DlmIaOFrauji8gYI0/x0ZIoFeBufubLr/4eE2gKfXKmbnjWDNPDhpdo+deAgUEBKwCqEoSILBaYElQOgSkNfeu7vg1BY59E/eziPj0yoazv3lb2R23EyAgYFkDBAi0JrAkIB3GcAhZc781uvztV02HjDHX7L+2CRC4IiBgWRIECLQkkLmP6pz9Wy0YLAlZpR5rtuChDwS6FhCwup4+nScwlECLvwTcGri3b9629tEegW4EBKxupkpHCQwvUPMsq5Zwr3vB9OVfTn4jIt5qqdP6QoDAewUELCuCAIFWBGqdxt7K+PWDAIGBBASsgSbTUAh0LlDjfYKdk+k+AQKtCghYrc6MfhHYn8A7yUP2+ZYMqhwBAvMFfADNt3IlAQJlBQSssr6qEyCwoYCAtSG2pggQOCrgEaEFQoDAMAIC1jBTaSAEuhA4djbV9G83kkbhxcdJkMoQILBMQMBa5uYuAgTOF5h7xtP5lR++w4uPMxTVIEBgsYCAtZjOjQQInCGw5JTyM8q/51IvPl4q5z4CBNIEBKw0SoUIELhGYMtwNXXBi48tRQIEqgsIWNWnQAcIDC2Q8W7Bc4C8m+8cLdcSIFBMQMAqRqswgd0LZL1bcC6kcDVXynUECBQXELCKE2uAwG4FMt8teAxx2nN1JyLu7lbawAkQaE5AwGpuSnSIwDACme8WnELU/Yi4eaFz+cXH9y7+bRg4AyFAoH8BAav/OTQCAq0KODi01ZnRLwIEigsIWMWJNUBgtwJefbPbqTdwAgQELGuAAIFSAgJWKVl1CRBoXkDAan6KdJBAtwIeEXY7dTpOgMBaAQFrraD7CRC4TiBzk7t3C1pnBAh0JSBgdTVdOkugqsB0rtV0cOjnI+LJGb/oyzymwbsFq069xgkQOFdAwDpXzPUE9ikw90XNl8+kyjpo1LsF97nmjJpA1wICVtfTp/MENhFY8i7Bw6nqGa/K8W7BTaZZIwQIZAoIWJmaahEYT2BJuDooHEJWRo3xZI2IAIGhBQSsoafX4AisEsj89mlJyPJuwVXT52YCBGoKCFg19bVNoF2BEvunluzjaldIzwgQIHBEQMCyPAgQeJRAqV8ATsHt6Yi4PfOXiGaHAAECXQoIWF1Om04TKC7gDKvixBogQGBkAQFr5Nk1NgLLBZzCvtzOnQQIEAgByyIgQOBRAt4jaF0QIEBghYCAtQLPrQQGFhCwBp5cQyNAoLyAgFXeWAsEehTwiLDHWdNnAgSaERCwmpkKHSGwicDcX/H9x8Uv/TI65UXNGYpqECDQlYCA1dV06SyBVQLnnEP1nxHxhVWtvXuzFzUnQSpDgEA/AgJWP3OlpwTWCCw5Sf3XEfHhNY1GhBc1rwR0OwECfQoIWH3Om14TOEdgSbg6p/6xa72oOUtSHQIEuhIQsLqaLp0lcLZAxvsEz2704gbvElwq5z4CBLoXELC6n0IDIHCtQNb7BJc8KhSuLEwCBHYtIGDtevoNfnCBzPcJfisi/iIibpwwm/Zc3YmIu4PbGh4BAgSOCghYFgiBcQWy3yf4l17UPO5iMTICBHIFBKxcT9UItCTgsNCWZkNfCBDYlYCAtavpNtidCXjdzc4m3HAJEGhHQMBqZy70hMA5AnNOZH/5nIIzrvV5MQPJJQQIEJgEfGBaBwT6E5h7IvvbEfFY0vDefLBx/VZSLWUIECAwvICANfwUG+BgArUODfU+wcEWkuEQIFBWQMAq66s6gUyBWuFqGoP3CWbOpFoECAwvIGANP8UGOIhAzRPZvU9wkEVkGAQIbCcgYG1nrSUCSwWyTmRf2r73CS6Vcx8BArsVELB2O/UG3pFA5ons5w7bK2/OFXM9AQIE/IrQGiDQhUDmieznDFi4OkfLtQQIELgk4Bssy4FA+wKZJ7LPObrB+wTbXxN6SIBA4wICVuMTpHsEIiL7RPbpF4G3I+LJiLh5ITydc/VGREzHMdx78MLm++QJECBAYLmAgLXczp0EthLIDlj+7reaOe0QILBbAR+0u516A29EYM4rb/7h0jdNa7vtRPa1gu4nQIDADAEBawaSSwgUEpj7ypvfRMQHk/rgRPYkSGUIECBwTEDAsj4I1BGodSq7E9nrzLdWCRDYmYCAtbMJN9wmBGqFKyeyNzH9OkGAwB4EBKw9zLIxtiRQ85U3TmRvaSXoCwECQwsIWENPr8E1JlDzlTcODW1sMegOAQJjCwhYY8+v0bUlUOuVN8JVW+tAbwgQ2IGAgLWDSTbEZgQyX3kz55eFTmRvZup1hACBvQkIWHubcePdQuC6s61+GxHvT+rAdJ7VPzqRPUlTGQIECCQLCFjJoMrtXmDu2VYZUP5+MxTVIECAQAEBH9AFUJXcrcDWxy/4+93tUjNwAgRaF/AB3foM6V8vAluHK6+86WVl6CcBArsUELB2Oe0GnSxQ42wrr7xJnkTlCBAgkCkgYGVqqrVHgVpnW3nlzR5XmzETINCNgIDVzVTpaKMCNc628sqbRheDbhEgQOAgIGBZCwTWCWSebTW3J155M1fKdQQIEKgkIGBVgtdstwLXnXG11YCcyr6VtHYIECCwQkDAWoHn1t0JbHnG1aNwhavdLTkDJkCgVwEBq9eZ0++tBbY+huHy+LzyZuvZ1h4BAgRWCghYKwHdvguBrcLV5VfpTOdcvRERr0fE3Yi4vwtpgyRAgMAgAgLWIBNpGMUEtjzjytlWxaZRYQIECGwrIGBt6621vgS2PuPK2VZ9rQ+9JUCAwLUCApbFQeB6gS3PuHK2lZVIgACBgQQErIEm01DSBbY848rZVunTpyABAgTqCQhY9ey13K7A4ayrf4mID23QTccvbICsCQIECGwpIGBtqa2tHgS2PutKuOphVegjAQIEzhQQsM4Ec/nQAlsdxzAhOttq6KVkcAQI7F1AwNr7CjD+g8AW4epwttV0HMM9Z1tZfAQIEBhXQMAad26NbL7AFmddOeNq/ny4kgABAt0LCFjdT6EBrBTY6qwrZ1ytnCi3EyBAoCcBAaun2dLXEgJfiYh/LVH4Uk1nXBUGVp4AAQKtCQhYrc2I/mwpMD0anH7F98HCjTrjqjCw8gQIEGhNQMBqbUb0ZyuBLTa1T2NxDMNWM6odAgQINCQgYDU0GbqymYBwtRm1hggQILBPAQFrn/O+51Fv8YtBZ1zteYUZOwECBCJCwLIM9iRQ+heD/xsRfxsR34iIt/YEa6wECBAg8F4BAcuK2JPAsxHxcsEBO+uqIK7SBAgQ6ElAwOpptvR1rcBrEXF7bZEj9zvrqiCu0gQIEOhJQMDqabb0da3Af0fER9YWueZ+Z10VglWWAAECPQoIWD3Omj4vESj9y0FnXS2ZFfcQIEBgUAEBa9CJNaz3CJT+5aCzriw4AgQIEHiPgIBlQYwuUPqXg8LV6CvI+AgQILBAQMBagOaWrgRK/XLwNxHxXETc7UpDZwkQIEBgEwEBaxNmjVQUKPXLwa9GxEsVx6VpAgQIEGhYQMBqeHJ0LUXgxxFxM6XSu0X8YjAZVDkCBAiMJiBgjTajxnNV4J0CJH4xWABVSQIECIwkIGCNNJvGclWWOjSkAAAEGUlEQVRg2uCe/coam9qtMwIECBA4KSBgnSRyQccC2RvcfxURf9yxh64TIECAwEYCAtZG0JqpIpC9wd27BqtMo0YJECDQn4CA1d+c6fF8gewN7t41ON/elQQIENi1gIC16+kffvDZG9wfj4j7w6sZIAECBAisFhCwVhMq0LBAdsDy99LwZOsaAQIEWhLwP4yWZkNfsgUyHxG++eDU9lvZHVSPAAECBMYUELDGnFej+r3A9yPiT5MwfhARn06qpQwBAgQIDC4gYA0+wTsfnoC18wVg+AQIEKglIGDVktfuFgIeEW6hrA0CBAgQeEhAwLIoRhawyX3k2TU2AgQINCwgYDU8Obq2WkDAWk2oAAECBAgsERCwlqi5pxeBn0fEE0md/UVEfCypljIECBAgMLiAgDX4BO98eD+JiBtJBj+NiE8k1VKGAAECBAYXELAGn+CdD883WDtfAIZPgACBWgICVi157W4hYA/WFsraIECAAIGHBAQsi2JkAQFr5Nk1NgIECDQsIGA1PDm6tlrAOVirCRUgQIAAgSUCAtYSNff0IvBaRNxO6uy3I+KppFrKECBAgMDgAgLW4BO88+E9++CXfy8nGXw5Il5JqqUMAQIECAwuIGANPsE7H94HImJ6TLj2qIbpiIZbEXF/556GT4AAAQIzBQSsmVAu61bgSxHx6sreP/MgYN1dWcPtBAgQILAjAQFrR5O946F+LSKeWzj+FyPi+YX3uo0AAQIEdiogYO104nc47CUhS7ja4UIxZAIECGQICFgZimr0IjA9Lnxhxp6sac/VHY8Fe5lW/SRAgEB7AgJWe3OiR2UFpo3vT18c3/Dkg/1ZNy+aezMi3oiI1y+ClQ3tZedBdQIECAwtIGANPb0GR4AAAQIECNQQELBqqGuTAAECBAgQGFpAwBp6eg2OAAECBAgQqCEgYNVQ1yYBAgQIECAwtICANfT0GhwBAgQIECBQQ0DAqqGuTQIECBAgQGBoAQFr6Ok1OAIECBAgQKCGgIBVQ12bBAgQIECAwNACAtbQ02twBAgQIECAQA0BAauGujYJECBAgACBoQUErKGn1+AIECBAgACBGgICVg11bRIgQIAAAQJDCwhYQ0+vwREgQIAAAQI1BASsGuraJECAAAECBIYWELCGnl6DI0CAAAECBGoICFg11LVJgAABAgQIDC0gYA09vQZHgAABAgQI1BAQsGqoa5MAAQIECBAYWkDAGnp6DY4AAQIECBCoISBg1VDXJgECBAgQIDC0gIA19PQaHAECBAgQIFBDQMCqoa5NAgQIECBAYGgBAWvo6TU4AgQIECBAoIaAgFVDXZsECBAgQIDA0AIC1tDTa3AECBAgQIBADQEBq4a6NgkQIECAAIGhBQSsoafX4AgQIECAAIEaAv8PNaUmvjP4p2kAAAAASUVORK5CYII=\"",
            "creator": {
                "userId": 6,
                "nickname": "Adolfo",
                "creationDate": "2024-04-25",
                "status": "OFFLINE",
                "persistent": null,
                "email": null,
                "password": null,
                "avatarId": 4,
                "role": "player",
                "token": "888c3a57-eb4e-4b26-8724-b3efdb1cfbb2",
                "gameRoom": null
            },
            "creationDateTime": "2024-04-25T13:10:03.142334",
            "gameSessionId": 1,
            "assignedTo": 3,
            "round": 6,
            "previousTextPrompt": 5,
            "nextTextPrompt": 7
        },
        {
            "textPromptId": 7,
            "content": "agagda",
            "creator": {
                "userId": 3,
                "nickname": "Greta",
                "creationDate": "2024-04-25",
                "status": "OFFLINE",
                "persistent": null,
                "email": null,
                "password": null,
                "avatarId": 1,
                "role": "admin",
                "token": "79e902ba-5a46-4329-b2b0-1549eb46766d",
                "gameRoom": null
            },
            "gameSession": {
                "gameSessionId": 1,
                "creationDate": "2024-04-25",
                "token": "0d529e1d-2d4c-4d41-b43e-f57b53c307a9",
                "status": "IN_PLAY",
                "usersInSession": [
                    3,
                    6
                ],
                "roundCounter": 8,
                "currentIndex": 0,
                "gameLoopStatus": "PRESENTATION"
            },
            "assignedTo": 6,
            "previousDrawingId": 6,
            "nextDrawingId": 7,
            "round": 7
        },
        {
            "drawingId": 7,
            "encodedImage": "\"iVBORw0KGgoAAAANSUhEUgAAAlgAAAGQCAYAAAByNR6YAAAAAXNSR0IArs4c6QAAIABJREFUeF7t3c2vdldZB+CborERg000eQeFBEeOpOlYBog6MJb4B2ggBuWj1OjQAQMHHTjUIB+lfWMgMXFq1DhCMGHeUBk4k4EMTCRBk5oaSrWbvg8+nJ5z9te99l4fVyeEvHvfe61rrfM8v7P32uu8I/xHgAABAgQIECCQKvCO1GqKESBAgAABAgQIhIBlEhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQICBgmQMECBAgQIAAgWQBASsZVDkCBAgQIECAgIBlDhAgQIAAAQIEkgUErGRQ5QgQIECAAAECApY5QIAAAQIECBBIFhCwkkGVI0CAAAECBAgIWOYAAQIECBAgQCBZQMBKBlWOAAECBAgQuFXgJyLiYxHxTEQ8HRFPPjrqOxHxckT8XUQ8jIjXe/ATsHoYRX0gQIAAAQJ1C/xeRDwfEQ9mmvnvbwasz0TES3V3Z751Ata8kSMIECBAgACB5QJ33alaXiHiLyLiD9acUNuxAlZtI6I9BAgQIECgXYGld6qW9LDpkCVgLRlixxAgQIAAAQJzAp+LiGfnDlr577/f6uNCAWvlSDucAAECBAgQeJvAVyPiQwVcpjVZ742I7xeoXbSkgFWUV3ECBAgQINC1wLTe6lsR8YsFe/nJiHihYP0ipQWsIqyKEiBAgACB7gWm9VZ/HhE/Xbin0/YNHy58jfTyAlY6qYIECBAgQKB7gc9GxHMH9XLaJ+s9B10r7TICVhqlQgQIECBAYAiBEovZ5+CayyvNNXhuBPw7AQIECBAgUEzgyxHxkWLV7y7cXF5prsEnDKpLEiBAgAABAhFn3Lma3D0iNPsIECBAgACBrgQuu7L/cUS876SeWeR+ErzLEiBAgAABAvkCmbuy72mdbRr26DmXAAECBAgQqEbgyLcE7+u0jUarmRIaQoAAAQIECOwRqCVcTX3wp3L2jKRzCRAgQIAAgSoEpseCL1bRkgh/7LmSgdAMAgQIECBAYL3AZSH7tFv6b0TEY+tLpJ/RdLiaNGzTkD4nFCRAgAABAs0I1LKQ/QL23xHxh2/u3P5SM4J3NFTAan0EtZ8AAQIECGwTqGmt1dSDr0fEr0fE69u6U9dZAlZd46E1BAgQIEDgCIGawtX0puBnerhrdT1wAtYR09g1CBAgQIBAPQI1LGR/NSK+FhHTJqIPe7lrJWDVM8m1hAABAgQIlBS4LGB/JiKefvMNwSdLXmxB7W7WWM311R2sOSH/ToBAtsD1G0u/HBFP3HGB70fEv0TEFx69Nt7FuoxsTPUI3CNQ2wL2f4qIX+vxbtVtYyBg+dkkQOBIga0f+FO4+uuI+N1RPpyPHBTX6lKgpjVWE/BXIuKjXUrf0SkBa6TR1lcC5whk/rHYYR4vnDNUrtqJQG3h6vMR8elObBd3Q8BaTOVAAgQ2CGy9YzV3qeY3IZzroH8nsFGghgXs100f9mdVwNo4g51GgMCsQOnfoof94J6Vd0DvAnctXP9ORPx8RPxUBQBdbr2wxlXAWqPlWAIElgqUDleXdjT7h2CXQjqOwA2BUneFs6C/HRF/2uvWC2uQBKw1Wo4lQGBOYPrN+i8j4nfmDkz69+m35PdY+J6kqUztAkf94rLVwV3lKzkBa+s0ch4BAjcFzvrN+pMR8YLhINC5QM3havjHgbfNPQGr859I3SNwkMCZH/6vRMRTB/XTZQicIVDbwvXJ4I2I+IeI+FuPA2+fEgLWGT8qrkmgL4Ezw9Xlg35a1Gsj0r7mld68JTA9dv+3NzfcfVAZiPWPMwMiYFU2YzWHQGMCH6/k8ZzHhI1NHM39kcB9bwS+HBH/GRG/XZmXtVYLBkTAWoDkEAIEbhWYwtX0Z2weq8Bn+oOxH66gHZpAYI3AWesW17Tx5rHC1UI9AWshlMMIEPgxgbMfC94cjlcj4meMEYGGBGr7GZqjs5B9TujGvwtYK8EcToBA1PrFYE2IydmKQK0/Qzf9po1Lp8eU0x3ih9Y5rpteAtY6L0cTGF2gxreZLmNiT6zRZ2cb/a/5Z+gi6JeVhLkkYCUgKkFgEIFa32a65rfYfZDJ2Gg3W/gZssYqaXIJWEmQyhDoWGD6Uph+6342In6p8n5a7F75AA3evOkXgOnFkFr/E64SR0bASsRUikCHAq295TStGZn+dI7/CBwhMLfFws21S9OmnM8c0bCV17CAfSXYksMFrCVKjiEwpkArC3Fvjo7PtTHn69G9XvrLx3V4mTYMffLohj663v9ExH9cXd8C9sID4YOoMLDyBBoVaDVcTdwW6DY66Rpq9pafj+nx23Mn9tHPxcH4AtbB4C5HoAGBFt5yuo/R24QNTLKGm7glXJ3dXWurThgBAesEdJckULHAGW85TY8qsh+beJuw4knWcNNa/OVDuDppwglYJ8G7LIFKBT4REV88sG3Th/+3ClzT24QHDuIglzrjl489tBau79FLOFfASkBUgkBHAke+5XT5zbrEF5e3CTualJV05ehfPua6/VcR8bMR8bSF63NU5/y7gHWOu6sSqE3g8rr5n0XE44Ub90ZEfCoivnR1nRKPXny+FR7IDsqv2WbhyF8+5mitM5wTquDffQBVMAiaQOBkgaWvm2c1c7oTcB2uLnX/N+sCj+r4fEsG7azc0nl/edT2JwXWCm4l9UbgVrkDz/MBdCC2SxGoUODoN6LuW3CbuUeQR4QVTraKmnT0vM/sukXrmZoFawlYBXGVJlC5wNFfMnNfDJmPYF6JiKcq99e8cwSOnvd39XLLvlhzP0PniLrqrQIClolBYEyBEmue7pJc+jZT5t9p+6+I+LmIeH3M4dXrOwSOnPf3DcLlDuvax5QvGdl2BASsdsZKSwlkCZR4a++2tv1zRHwuIh4uDDpTu74bEe9O6qi9sJIgOylz1LxfwnW9jciahfZLajumEgEBq5KB0AwCBwoc8br51recvhkR70+ysBdWEmQnZY6Y90uphP+lUg0fJ2A1PHiaTmCjQOZap7uasPUtJwvdNw7qAKftvdNzxLxfMgzTLx/vjYjvLznYMe0KCFjtjp2WE9gqkBlibmvDnoW4tmrYOqp9n5exVqn0vF86Alt/+Vha33GVCAhYlQyEZhA4UCA7xFw3fU+4mupkt81n3IETq9Cltrz1d9s8zJ5bW7q79+djyzWdc5KAD5+T4F2WwAkCl0csJf7W4NI3Bee6nXmXwV5Yc9r1//uWcHXp1c0wc3bAEq7qn2+pLRSwUjkVI1CtwNJHLGs78FpE/NGKNwXn6meuk7HIfU677n/P2FLh+nFcdnifdnZ/PiIezDBm/fJR92hp3dsEBCyTgkD/AnvuAszpZIeYzDe9vKk1N3r1/nvWlgrXb7OWCO97F97XOwJatltAwNpNqACBqgVKhqup49khpsQXa9UDNFDj1oSREkE7cyPb7Hk/0DQYp6sC1jhjrafjCWQ8YrlPbeteV3Mj8eWI+MjcQTP//pWI+OjOGk7PE1j6iPryOO23IuKZpMtf7rIK70mgyiwTELCWOTmKQGsCWV8m9/W7xOvmWe0uFf5amwc1tHfLXdRXI+JdSY2/ftkh45eOEvM+qavK1CQgYNU0GtpCIE8g8xHLba0q9UZUZrs9xsmbT1srbQlXW69133nX33V72lRq3pfos5onCwhYJw+AyxMoJJC5oPdmE0t+yWS2O3sBfqGh6rZsxt2iLJyb33VbQlbJeZ/VT3UqEhCwKhoMTSGQKJD5SvqlWUe8bp7ZbvtgJU6olaWyHvWuvOyth981D9auC3spozFqjCMgYI0z1no6lkD2porT47aHEfF6YcbsdvuMKzxgd5TPfNS7twf33clc82bj3nY4fzABHz6DDbjuDiEwfWlk/yHZoz4rBKw+pmjmo969Itbi7RV0/iaBoz40NzXOSQQIrBZY+thjTeEjH7V5RLhmZI47du2dnsxx3NNLb5Pu0XPuLgEBaxefkwlUJbBl4e6SDhy5WDzzzseR7V7i2OoxS0P79Rq97DuRW+1sqbBVznm7BQSs3YQKEKhCoFS4mjp35COWzLU7R7a7iklQoBFb5tX0tt1zBdqytqS3/taKOT5VQMBK5VSMwCkCJV+HP/oRS9bbZ0e3+5SBL3zRLeHq0qTMjUK31BKuCk8O5ecFBKx5I0cQqFkgK5Dc1cczHrFkBMZ/jIhfrXngKm9bxhhkdXF61Ps3EfF8RDyYKXrEViJZ/VKncwEBq/MB1r3uBTL/gO1NrDPvAnw1Ij60c/TOCIc7m1zF6aVD+9pOXh71rl1ov/Y6jieQKiBgpXIqRuBwgcxF4deNPzNcZX3Be0y4bTqWDO1rW2QM14o5vhoBAauaodAQApsEsl+Hr+ERS+YXvIXu66dVqdC+viUR7kJuUXNOFQICVhXDoBEENgtkvw7/kwfs1j7X2cwveFs1vKW95vFaZmjfskD9Mj/OvIs6N0f9O4FZAQFrlsgBBKoWyA5YNXwmZH7BH7lJaq0TZe0+Vi8md2TLtg3CVfIgKHe8QA0fpsf32hUJ9CEwfXG+EBGPJXWnljDSY2hMGqLVZfZstbD6YnecMH3PrA15/rBylr46pwkIWKfRuzCBXQIlvjhreZwmYO2aGj86ucQcWduy69C+5jHl2us4nkB1AgJWdUOiQQRmBUp9cdayINwjwtkpMHtALftY1RLaZ8EcQCBbQMDKFlWPQFmBUl+cNb0Ob5H7vjmUtc3Fvla8dXYtoT2jL2oQWCUgYK3icjCBUwVKfnHW9Dq8v0e4b5plbnOxpyU1hfY9/XAugU0CAtYmNicROEUgM3hcd6C2N7ayguSoX/CZdwD3TPSaQvuefjiXwCYBAWsTm5MInCJQ4ouztnB1gc14FDrqF3zmGratE73WebW1P84jsFpAwFpN5gQCpwlkfnG+ERHTHbGaX4f/ZkS8f6P2KxHx1MZzazlt61t32W9hrvUQrtaKOb5LAQGry2HVqU4Fsr84a/75H/0O1p59o7LnyXQn8PmIeDDzc1XDn1nq9Edft1oUqPkDtkVPbSZQUiD7i7PWn//R12Bt2Ybj+q5R5p3Oyz5WW++mlfx5UJtA1QK1fsBWjaZxBE4SKPHFeVJX7r1s5ltwrW0TsCVcXTAvIStzrZ59rGr8CdGmJgQErCaGSSMJ/FBglC/OUfp5c1pnPRZ9Z0R8MelnprWAmtRtZQjsFxCw9huqQOAoga9FxAeTLlbzF+cod+quhzLzsej7IuLbC9ZMzU2lUbe5mHPx7wQWCQhYi5gcROB0gYy7G5dO1P7FOcpas+tJlbnH2RSefxARL+6ctaNuc7GTzekE3hIQsMwEAvULZN3duPS09i/OEQNWiceiGeu56v/p0EIClQoIWJUOjGYRuBLIvLvx9Yj4lcp1e3xEOPcW3gci4omkcbm8+TeV2xKy7GOVNBDKjC0gYI09/nrfhkCJuxs197y3/i7d0ypzTK4/25de3z5WmSOg1vACAtbwUwBAAwI93tG5jz3zjt3Zi/m33EHKmJI3P9vn7qBN2zE8jIjXMy6uBgEC1mCZAwRaEBhtTVLWmrOzF/OfFa6uHxG2ML+1kUCXAu5gdTmsOtWZwGgBaxq+jLcmz1zMn9H+rdPY5qBb5ZxHIFFAwErEVIpAIYHRHhFeGPfcATpzoXbWHbit0+nsx6Jb2+08Al0JCFhdDafOdCrQ26LvNcP0zYh4/5oTIuKViHhq5TmZh2f+qZ+17Tr7seja9jqeQLcCAla3Q6tjHQn0tOh7zbC0egcrMxCv8ZqOPfOx6Nq2Op5A1wICVtfDq3OdCHwuIp5N6EtLdzcy1jCdFTYyH+muGfYzH4uuaadjCQwhIGANMcw62bBARtC4dP+swLGWP2sNU2agXLPNQfZLCUv8hKslSo4hcKCAgHUgtksRWCmQFTSmy34+Ij698vpnHZ65hiljwffajTr3/g3ANe42B12j5VgCBwoIWAdiuxSBlQKjrr3KXMO0d8uCLevAXo2Id60c67sO/15EfCMinn7zjzc/+eigaZ+rlyPC5qBJyMoQKCEgYJVQVZNAjkBNQSOnR8uqZK5h2rPp5pZwtayHy4/aGxCXX8mRBAikCghYqZyKEUgVqCVopHZqQbHsNUxbPucy174t6PKdh2Q84txzfecSILBRYMsHz8ZLOY0AgZUCNQSNlU1OOfzsfmeufdsDkrlIf087nEuAwAYBAWsDmlMIHCRwdtA4qJtvu8zZd+4y177tMWzlrc89fXQugW4FBKxuh1bHOhA4O2icRXj22rPM6281tO3CVjnnEahEQMCqZCA0g8AtAplf9C0tls68g3TfGqa79rb6QUS8M2lGbnmjULhKwleGwJkCAtaZ+q5N4H6Bo4JGbeOQtQbqvjVMS/e2yrCZHvU9HxEPZorZ0ypDWw0ClQgIWJUMhGYQuEXgiKBRK3zGW3x3rWE6evuF6XN2zU7wtY6JdhEgsEJAwFqB5VACJwh8OSI+svO6X4mIj+6sccbpe4LQXY/Z9tTcYrBnH64t13MOAQKVCAhYlQyEZhBwB+vWObAlEN0VrjLuiq2dqC2tfVvbN8cTIHCPgIBlehCoV2DUNVjXI5IVsLIet66dLTYKXSvmeAKdCAhYnQykbnQpMOpbhJfB3BKuLufevIuVGVaXTjYbhS6VchyBDgUErA4HVZe6ERh1H6xpADMe501/KPmJR7PhtYh4/OCZYaPQg8FdjkBNAgJWTaOhLQR+XGDUndzPepyXOf/sZZWpqRaBBgUErAYHTZOHERg1YJ3xOC9zUglXmZpqEWhUQMBqdOA0ewiBUR8RZq49O3Ki2Cj0SG3XIlC5gIBV+QBp3tACmUGjpe0CMoNliQl0/ad0pn2uXo6IyfdhRLxe4oJqEiDQnoCA1d6YafE4ApmPylraLiD70Wj2jGkprGb3XT0CBBYKCFgLoRxG4ASBzMXeU1j70gl92HLJ2gNWS2F1i79zCBBIEBCwEhCVIFBQ4OMR8UJC/Zb2ZKr5EWFLjgnTRgkCBLYKCFhb5ZxH4BiBER8TZq49yx4le1tli6pHoFMBAavTgdWtbgQyw0Yra4emR3BfqHAEbb9Q4aBoEoFaBQSsWkdGuwi8JZD5uGx64+09DcBmrj3L6q5wlSWpDoFBBASsQQZaN5sVyF7w3crPfMafyskYdHtbZSiqQWBAgVY+bAccGl0m8EOBUQPW1PevRsSHDpoH13+r0N5WB6G7DIGeBQSsnkdX33oQGOkR4fRo8GMR8UxEPB0RTx44gLZeOBDbpQiMICBgjTDK+tiywCiL3KdHgs+/ubj9wQmDZeuFE9BdkkDvAgJW7yOsf60LfCoiPp/UiWcrfTvvsxHxXFIft5Sx9cIWNecQIHCvgIBlghCoW6D3gHV2uPJ2YN3zX+sINCsgYDU7dBo+iEBvjwiv11l9ICKeOHEchasT8V2aQO8CAlbvI6x/rQv0tMj9zHVW1/PA1gut/1RoP4EGBASsBgZJE4cW6GWbhrMfBdp6YegfI50ncLyAgHW8uSsSWCOQHbCOeCw2PQac7lb95gnbLdxm28qfCFozLxxLgEDlAgJW5QOkecMLZD4ivGCWfGuulseA1xPHHlfD/xgBIHC8gIB1vLkrElgjkLnI/XLdUvs+nf0Y8DbXUn1dM4aOJUBgQAEBa8BB1+WmBD4REV8s0OKMuzrXbwT+SkS8q0A795Ysebdub9ucT4BAxwICVseDq2tdCEwhZnpMmL3D+bcj4hd2CNX4KPBmd45Yb7aD0KkECPQsIGD1PLr61ovAFGZeLNCZpQHkzL8RuLXbS/u2tb7zCBAgcK+AgGWCEGhDoNT6ppuP0FoMU9cjaI+rNuazVhLoXkDA6n6IdbAjgewtGy40r0XE44/+zxsR8VhjZva4amzANJfACAIC1gijrI+9CJTYsqF1G4vYWx9B7SfQqYCA1enA6laXAiW2bGgZyjqrlkdP2wl0LiBgdT7AuteVQKktG1pEEq5aHDVtJjCQgIA10GDravMCpbZsaAnGIvaWRktbCQwsIGANPPi63qRAqS0basb4XkR8IyKmvyn4MCJer7mx2kaAAIFJQMAyDwi0J1Bqy4YaJTwKrHFUtIkAgVkBAWuWyAEEqhT414h4X5Uty2uUcJVnqRIBAgcLCFgHg7scgSSBnhe8W2eVNEmUIUDgPAEB6zx7VyawR6C3Be82C90zG5xLgEB1AgJWdUOiQQQWC/Sw4N1jwMXD7UACBFoSELBaGi1tJfB2gVYXvHsMaDYTINC1gIDV9fDq3CACX4uIDzbQ11cjYmqr7RYaGCxNJEBgn4CAtc/P2QRqEJjWY303It5dQ2PuaINHgRUPjqYRIJAvIGDlm6pI4AyBWtdjeRR4xmxwTQIEThcQsE4fAg0gkCZQy3osbwSmDalCBAi0KiBgtTpy2k3gdoGzQpY7VWYkAQIErgQELNOBQH8C0+PC5yPiQeGuXe5U/X1EvORvBBbWVp4AgaYEBKymhktjCSwWmBa+fywinomID0TEE4vP/P8D34iIxx79X4/9NgA6hQCBcQUErHHHXs/HErgOXE9HxJOPuv/ao/99XJAaa0LoLQECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAH9k4ZrAAAFBUlEQVQCAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMKCFgDDrouEyBAgAABAmUFBKyyvqoTIECAAAECAwoIWAMOui4TIECAAAECZQUErLK+qhMgQIAAAQIDCghYAw66LhMgQIAAAQJlBQSssr6qEyBAgAABAgMK/B/Kh+e+47GfYgAAAABJRU5ErkJggg==\"",
            "creator": {
                "userId": 6,
                "nickname": "Adolfo",
                "creationDate": "2024-04-25",
                "status": "OFFLINE",
                "persistent": null,
                "email": null,
                "password": null,
                "avatarId": 4,
                "role": "player",
                "token": "888c3a57-eb4e-4b26-8724-b3efdb1cfbb2",
                "gameRoom": null
            },
            "creationDateTime": "2024-04-25T13:10:15.227695",
            "gameSessionId": 1,
            "assignedTo": null,
            "round": 8,
            "previousTextPrompt": 7,
            "nextTextPrompt": null
        }
    ]

    const newArray = response.map(element => {
        if (element.drawingId === undefined) {
            return new TextPrompt(element);
        } else {
            return new DrawingPrompt(element);
        }
    });


    function TextToSpeech(text) {
        const synth = window.speechSynthesis;
        let speakThis = new SpeechSynthesisUtterance(text);
        console.log(synth.getVoices())

        speakThis.rate = 1;
        speakThis.pitch = 1;
        speakThis.voice = synth.getVoices()[50]
        speakThis.lang = "pl-PL";
        synth.cancel();
    }

    const testUser = new User();
    testUser.nickname = "Greta";
    testUser.userId = 3;
    testUser.avatarId = 2;
    testUser.role = "admin";

    const testUser2 = new User();
    testUser2.nickname = "anotherTestUser";
    testUser2.userId = 2;
    testUser2.avatarId = 3;
    testUser2.role = "player";

    const testTextPrompt1 = new TextPrompt();
    testTextPrompt1.creator = testUser;
    testTextPrompt1.content = "Ic hab voll in house gegaggeld sadface und ich bin trourig hahahahahahah asdfasdfasdfasdf";
    testTextPrompt1.numVotes = 3;
    testTextPrompt1.textPromptId = 1;

    const testTextPrompt2 = new TextPrompt();
    testTextPrompt2.creator = testUser2;
    testTextPrompt2.content = "Another test text prompt";
    testTextPrompt2.numVotes = 2;
    testTextPrompt2.textPromptId = 2;


    const testTextPrompt3 = new TextPrompt();
    testTextPrompt3.creator = testUser;
    testTextPrompt3.content = "cool inspring prompt written by a true poet";
    testTextPrompt3.numVotes = 1;
    testTextPrompt3.textPromptId = 3;


    const testDrawingPrompt1 = new DrawingPrompt();
    testDrawingPrompt1.creator = testUser;
    testDrawingPrompt1.numVotes = 2;
    testDrawingPrompt1.creatorId = 1;
    testDrawingPrompt1.encodedImage = "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAAAXNSR0IArs4c6QAAD2NJREFUeJzt3W1sluUVwPGna6lQqQIFSlukxCJZGvAluqFxkSxGTXXrlsygzmVm8206Q8ShcZHFKRgzZ9Q4cUPYix82I5nRMdQxIwsmRGNclJc0xtlFBApCnUil2CJ2X/bBc55xHS+v+37ezv/37XDfvZ/HosfrnOvlrhsZ6h8roGa98fr2XJ8/sGNH3P179gevt7dNi3pee2dn1P1Hu88OXp/RdHzU86rdl8r9BQCUDwkAcIwEADjWUO4vAFSSvcOHRFzrPQFGAIBjJADAMRIA4Bg9ACCg1nsCjAAAx0gAgGMkAMAxegBABN0TSFXungIjAMAxEgDgGAkAcIweAFBG5V5nwAgAcIwEADhGAgAcowcAVJBS9wQYAQCOkQAAx0gAgGP0AIAKlndPgBEA4BgJAHCMBAA4Rg8AqCJZ9wQYAQCOkQAAx0gAgGP0AIAEl90wU8ST5tUH71/14x15fp1ojAAAx0gAgGMkAMAxegDAZ+iaXtM1vlXza9ev7BRxak8gdV0AIwDAMRIA4BgJAHCMHgBcsWp8y4HtR6Puj+0RpIrtCTACABwjAQCOkQAAx+gBOLPgvG+JuGlcvv8PaGtrFfGyJdeJePjIp7l+vuXw7rGkn5/QURd1v+4hZL0uIBYjAMAxEgDgGAkAcKxuZKg/rQhCRTuuuSvq/qx7AroHoOkewKP33RH1/PbOTvumz7j0V5eK2OoBtF0UbpPt2fCJiGN7ArHrBFJ7BHpdACMAwDESAOAYCQBwjHUANSa25k9lzeP3v7sneF33CG687R4R655E311Xqw/YJ+PWk0X4xsSW4Odb9Ly9VbNbPQXdI4jdW5BK7xVgBAA4RgIAHCMBAI6xDqDKlLrGt+gaPXVtf9esNvUn4f9H9d31g7gPUD2CjhXXHePG/0/X8Kl7CWI/78lf78r0+YwAAMdIAIBjJADAMXoAFa7Sav6sxe49aGuTPYL7zp4mYt2DWNTbG35gYk9A03sH9F6BWPQAAOSGBAA4RgIAHGMvQIWp9Zpf0zV7bE/gtlf2i1j3BEpNr+3PuieQNUYAgGMkAMAxEgDgGOsAKoy3HoCWui7A8vMz5fkAResEMl4XkGrdut25Pp8RAOAYCQBwjAQAOEYPoMJ47wFoqe8psHoE1nkCZ717f9TnWfP8em1/7HsBLLHvDWAEADhGAgAcIwEAjrEXoMyo+fO1Z0/4vQRr160TsV4XkPW5/cVnCIafr+/PuofACABwjAQAOEYCAByjB1Dj5p5Y3s9/68O0n089L8BiPS/2XX+xdA2vew7W81N7FIwAAMdIAIBjJADAMXoAVa7cNb7F+n6xPYKsewLWuwx3L3sseD31vAC9d0CfIWjdn9qDYAQAOEYCABwjAQCO0QMos0qv4fOW2iOwegL6+lOLTv/c361QKBQK7/1bhHXq+QN3rRFx+53XxD1fKfV7AxgBAI6RAADHSACAY/QAnHvm9utF/KPVa0W89/0Pkp6/7aFlIr5g+cqo58f3SMI9gce27BTx97o7op4+pnoKdapHoHsC+v7UdQN63j91HQQjAMAxEgDgGAkAcIweAFxLraGtnoBeqa/3Flg9gTVvy3UBPfvk9bpFV4i4r16tgzga3uvACABwjAQAOEYCAByjB1BlZrRMFnHsPL2e90+l5/nn37wi6Xmp/3yWTz4ZFfGj/+wX8fAR+Z4Ai36PgO4JaHX/eUfED7Z2i7h589aoz0/FCABwjAQAOEYCAByrGxnqDx98jlzNnxn3bkBdI//m2kXyhh45r7xx40YR33TLrSLuu1f2BLpmTIv6PoXv/kyETz/9tIgvv/xyEY889zsRz7/ihyK2egDWfn/tpKnNwevaltbDweu6Ztd0T0DT7yK0av6LW+Q/b9G6A7UOQOu79WER63UBjAAAx0gAgGMkAMAxegBllnkPQOsx9p8/Hz73PrUnUORPy8PXW08W4YLvh8/Ys84EbDnx+ODPWzW/xeoJaFbN33OCjPUZhJrVE6AHAOCYSACAYyQAwDH2AtQ6o8bX/r5pk4hvuOzSuM+zanyDVfNa8/6Wf80cEfGE6XLH/qR59VHPW7KhT8SxPQFd82vm3gLj99X9y8Uifu2Wh0TMCABwjAQAOEYCAByjBwChZUKj/AM1L6/flVdu1pl+DfXjRDw2/ePg/Qe2H436/LaL5H9Cuiegz/TLWlGPYO0TItTrAs564GYRMwIAHCMBAI6RAADH6AGU2bZd8ky62L0BNUf1GF59Qp4f8FV1foDW3Cwn1u9e83sRX3L7d6K+jn4Xn2b1DK6ZI/8T0z2B3RNkj0LrOHwkeN0yZvQEGAEAjpEAAMdIAIBj9ABQ1fTegLgTAG2Hd2d7XEZxT0DW+Ke2yp6A7hGk9gQ0RgCAYyQAwDESAOAYPQDnivb/L75N3pDz2v+i/exq74Ge9089D6DSlLonoNcFMAIAHCMBAI6RAADH6AE4d+HChSJunLxB3iBfQ1AYffOUpM+zav4nH31AxFbN3zplkojvf/zx4P3r1u0OXu/t7Qhen7tzvCi6O08cJ4ryF04YCv68RfcECgW5DuHVofDehFiMAADHSACAYyQAwDF6ANWuZaaM398VvH1gIDxv3PC3WfLxBb3ffTj48xNnN4nYqvn/ulqeU798Y/jdeXmzegRLzwif13DBQbkbIbUnoM8P0L8dHet1A5peN8AIAHCMBAA4RgIAHKMHUOFmtMiJ+Be2vBa8v/+R+4LX29tljTg8IM/JL675pYkL5sk/UHsFYuf5y13zp9rx4ZHgugCrp6Dt624Vsa7pt74na/iidwtG7g1gBAA4RgIAHCMBAI7RA6gxQ+deLOLmzc8F729qHy/iiTOajnHn/xjnA4xNmS3i9SWe51961VUitvYGlJtV8+t5e/3be/6gjIt6AgZGAIBjJADAMRIA4FjdyFB/tgefI4l+N6B+d6Dljde3i3jJlVeKDeRrbrwy6u+7a8a08A1qnn/9Hx4W8Td++1Twx7N+F6I+H6BJrUv4yaEDIp6+/T0RDx8Nnz+w9Iyu4ER7e7NcB3Dh4Afi+mz1feZMqRdx1uf+W+8eZAQAOEYCABwjAQCO0QOoMFn3ADRrXYCu+etmzhHxmDqjr27h14PPG/s07hz/1J6A1QNYPuFQ0vNbRsI1+ohxhuGcRvl99O8zlVXz7/2HPC+CEQDgGAkAcIwEADhGD6DG6B6AVfNr1ry/7gloVk3bv0vuj9/30N0iPmdU1tjz9wcfV6R1klwMv6rh4DHu/HyO0+cbRDpJHeNf6pp//8o/B68zAgAcIwEAjpEAAMc4D6DK6TMAm49xX2aM8wD0m+veHpY1qq75p+t5dfWAbaolEdsT6Ip8lV7RmYZKbA2f2mBLrfEtjAAAx0gAgGMkAMCxqu8B3HTJN6Pu/8qbfSKeO1XWWAcGw2u95y65Pnj9/IefEfGLi78d8e1Kz9zvHym25o+t0VN7Apas5+lj5V3za4wAAMdIAIBjJADAsarrAeia/7TOcA3buGGTiHXNr2vSWca72KpdbM1vzYvrmv+jlStErPfjd41GfbxJ9wQKhbS1/xZ9Dr8Wey6/VfPfO/kU+QfLfhq83/rvQWMEADhGAgAcIwEAjlX8eQB51/za+KZwTWb1BG6obwtef3Fxb/B6qtR5fV3z79wrJ9pHTmgXsZ7n1zX/6aPh31e5590tZa/5Fevf/6lTJwWva4wAAMdIAIBjJADAsYpbB1Dqmr9oLbp6N5uu2fT727XNhUER572OIOua/+2d8l15hZaZItQ1v3baoRH5B4ln6lUaq+bPu8bPWm397QCIQgIAHCMBAI6VvQcQW/Onit1/Hvu+dqtnsPXBVSK2zhfQMq/51Vp+q+bX5/bHKvW8v57Hj523t5S65o+d57cwAgAcIwEAjpEAAMdy3wtgndln1kDjZJuicf2LIrbm/WNr/qxZNaJeJ9Dzi2VJn2eeaz9ltohfXhruQaT+PvX3Se0BxJ7bH7uW37r/2S93h28wZL2WPxUjAMAxEgDgGAkAcCzzHkDyvP648NIE3QP4mnoZXmyNmvc8sRbbE7D2HmiNqkYejay5Y9c9xErtCaS+u8/6+9bXrZq/3PP4qRgBAI6RAADHSACAY8l7AfKu+ee98pKIpyfW/Jasz4DTrBq7Qz8/tiY/HHd7qeka3arp82b9fceqtBrfwggAcIwEADhGAgAci+4BxNb8Vk00+OFHItbz/AW11j/rml/X9HqePu95caSJnffXUuf5q63m1xgBAI6RAADHSACAY2YPoOQ1v5J6Bp2ma3y99n5So7z/3cbKPm+g2uW9LsDaS/Gsimu95tcYAQCOkQAAx0gAgGNFPYC8a36LPuOvkNgDsPbf6xrxzuPlmXlXH3wn6fNRWvrv2zqX31JrNb/GCABwjAQAOEYCABxryLrm16x5fk3PsxcynmfX8/5Fa8EzXneAbGW9biDvd1FWOkYAgGMkAMAxEgDgWEPWNf/4P/5FxHo7dtbv8rPm+WMt6J4l/+CV8DoA/VYF9gagmjACABwjAQCOkQAAxxryXuucdc2v6Xl9i573P/9MuVZc7114a1A+X7+XANmKnecvOhOwoT54v7f9/hZGAIBjJADAMRIA4FjyuwEHBw+IWB2pV4itqFLf1Wa9u69noE/+gYpXn3d+8Of3HRded9DFXoIk5X5XoDf8tgHHSACAYyQAwLHkHkAsPe9v1fxWTa+lPu/al9T5BfrdgWqa+ePhfM8vqHWpNX/qXhBv8/4aIwDAMRIA4BgJAHAsugeg5/01a+2/rpFja3xL1s+zasy3hmTclfHnV7vUGl+v9c/6/AfvGAEAjpEAAMdIAIBjJV8HUGlia0rr/IGs1zXEiv3n6Tgct3ch77X6u/R+fmN/v/meBwQxAgAcIwEAjpEAAMcy7wEUzftXGavGHzr31LQP2LY16cetGt/6/rE9CKvm36nei/C+Oi+hXZXwo/oMP0PsmY+IwwgAcIwEADhGAgAcy7wHUOnvxoudJ7dq/kW9vXFfILIHUOqaP9aIquknHhkR8Wtqr0Qs6/vr38+z6rr1HgDvGAEAjpEAAMdIAIBj0T0AfYaadT5ApdM1dOY1v3bHsvD1e1aIsNw1ftG79xSr58P5CJWNEQDgGAkAcIwEADiW+TqA1ecsFPG1L2/K+iNKKrnmj6V6BD2qJ4A03t8DoDECABwjAQCOkQAAx5J7ANa6AN0T2LJjf9TzHxno+2Jf7Atq3izX6q817i95jwDIECMAwDESAOAYCQBw7L/f+DmqLvySmwAAAABJRU5ErkJggg==";

    const [idx, setIdx] = useState<number>(0);

    useEffect(() => {

    }, idx)

    let toShow = newArray.slice(0, idx + 1);
    console.log(idx)

    console.log(toShow);

    const timerProps = {
        isPlaying: true,
        size: 60,
        strokeWidth: 6
    };

    return (
        <BaseContainer>
            {/* <Leaderboard
                topThreeTextPrompts={null}
                topThreeDrawings={[testDrawingPrompt1, testDrawingPrompt1, testDrawingPrompt1]}
                onClickNextRound={() => console.log("next round")}
                onExitGame={() => console.log("exiting game")}
                user ={undefined}
            >
            </Leaderboard>
            <Leaderboard
                topThreeTextPrompts={[testTextPrompt1, testTextPrompt2]}
                topThreeDrawings={[testDrawingPrompt1]}
                onClickNextRound={() => console.log("next round")}
                onExitGame={() => console.log("exiting game")}
                user={undefined}
            >
            </Leaderboard>
            <CountdownCircleTimer
                {...timerProps}
                colors="#000000"
                duration={10}
                initialRemainingTime={remainingTime & minuteSeconds}
                onComplete={(totalElapsedTime) => ({ shouldRepeat: false })}

                // Here submit if timer ran out
                onUpdate={(remainingTime) => (remainingTime === 5 && timerSound.handlePlay())}
            >
            </CountdownCircleTimer> */}
            <div className="gameroom header">
                <BurgerMenu
                    onClick={() => setOpenMenu(!openMenu)}
                    disabled={openMenu}>
                </BurgerMenu>
            </div>
            <PresentationContainer
                presentationContents={toShow}
                isAdmin={true}
                onClickIncrement={() => (setIdx(idx + 1))}
                onClickNextRound={() => console.log("clicked next round")}
                onClickResults={() => { }}
                gameSession={undefined}
                user={testUser}
            ></PresentationContainer>
            {Menu(openMenu, toggleMenu)}

            {/* <Button
                onClick={() => TextToSpeech(testTextPrompt1.content)}
            >
                CLICK TO SPEAK
            </Button>
            <DrawContainer
                height={400}
                width={600}
                user= {testUser}
                game= {null}
                textPrompt={testTextPrompt1}
                timerDuration= {100}
                setNextTask={() => console.log("nexttask")}
                setInitial={() => console.log("setInitial")}>
            </DrawContainer> */}
        </BaseContainer>
    )
}

export default SandboxView;